version: 2

sources:
  - name: reference
    database: tpc_di
    schema: digen
    loader: snowpark

    tables:
      - name: status_type
      - name: industry
      - name: date
      - name: tax_rate