version: 2

sources:
  - name: digen
    database: tpc_di
    schema: digen
    loader: snowpark

    tables:
      - name: cmp
      - name: sec
      - name: fin
      - name: status_type
      - name: industry
